name: corona_module
description: Corona module for Samachar Hub app.
author: Sujan Parajuli

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.1
  assets_audio_player: ^2.0.9+2
  line_awesome_icons: ^1.0.4+2
  google_nav_bar: ^2.1.0
  simple_coverflow: ^0.0.8
  loading_indicator: ^1.1.0
  auto_size_text: ^2.1.0
  sliding_up_panel: ^1.0.1
  url_launcher: ^5.5.0
  flutter_map: ^0.9.0
  fl_chart: ^0.11.0
  intl: ^0.16.1
  animator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icon/icon.png

  fonts:
    - family: Sen
      fonts:
        - asset: lib/assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Sen-Regular.ttf
          weight: 500

    - family: Sura
      fonts:
        - asset: lib/assets/fonts/Sura-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Sura-Regular.ttf
          weight: 500