name: samachar_hub
description: News aggregator app of different nepali news sites.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  line_awesome_icons: ^1.0.4+2
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  url_launcher: ^5.7.10
  rxdart: ^0.24.1
  flutter_bloc: ^6.1.1
  flutter_advanced_networkimage: ^0.7.0
  cached_network_image: ^2.3.3
  uuid: 2.2.2
  timeago: ^2.0.28
  webview_flutter: ^1.0.7
  intl: ^0.16.1
  path_provider: ^1.6.24
  equatable: ^1.2.5
  validators: ^2.0.1
  flutter_staggered_grid_view: ^0.3.2
  
  firebase_core: 0.5.2
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.3
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3
  firebase_in_app_messaging: ^0.2.2
  firebase_dynamic_links: ^0.6.2
  flutter_facebook_auth: ^1.0.0+3
  flutter_twitter: ^1.1.3

  carousel_slider: ^2.3.1
  nepali_utils: ^2.2.1
  fl_chart: ^0.12.0
  animate_do: ^1.7.3

  flutter_local_notifications: ^3.0.1+3

  flutter_signin_button: ^1.1.0
  flutter_share_me: ^0.9.2
  flushbar: ^1.10.4
  launch_review: ^2.0.0
  data_connection_checker: ^0.3.4
  shimmer: ^1.1.2
  dio: ^3.0.10
  get_it: ^5.0.1
  event_bus: ^1.1.1
  scoped_model: ^1.1.0
  uni_links: ^0.4.0
  readmore: ^1.0.0

  # corona_module:
  #   path: ./corona_module

dependency_overrides:
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  onesignal_flutter: ^2.6.1
  flutter_launcher_icons: "^0.8.1"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  image: assets/icons/logo.png
  color: "#FFFFFF"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
